language: node_js
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- 10.6.0
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem update --system
install:
- cd log4js
- npm ci
before_script:
- npm ci
script:
- grunt --gruntfile "Gruntfile.js" build
deploy:
  - provider: npm
    email: stephan@st-strittmatter.name
    api_key:
      secure: NQyGsxZKqApzTxBjsXMI/2drQcCF8s38iuofEL/wbATWC9Y9ggfI6oyd/tqqyYrgouBoSqHPSOEP4ghe381yrO9jlnJMiwzmLqVivZAAe4x2DI3nrlaz+AFcvTpf/36T4LFevTP3Lh6LoVGRrKnfRCjQzfBv0hYOLtjNCc/zjeU=
    file_glob: true
    file: target/*.zip
    skip_cleanup: true
    on:
      tags: true
      repo: stritti/log4js
  - provider: releases
    api_key:
      secure: iKdorqXgiTH3RcLLNj8Q4AoRWxpYA6yT7YDYKnuORz3tcAvHrIBmt+ff6h5zsn2JVGkFamc0njfYdrOfLdc4+cQQfQVq80OhJJnkIQ0WgOtG0yt+yVHKb8lWBGr9P0lMvvBuROsuxGl9jPcgkUTtuvxHoJ3T24WlLDGXJSWdCzw=
    file_glob: true
    file: target/*.zip
    skip_cleanup: true
    on:
      repo: stritti/log4js
      tags: true